#!/usr/bin/env bash
#This script is used for displaying numbers 1 to 100

count=0

while ((count <= 100)) 
do 
	if (( ("$count" % 3 == 0) && ("$count" % 5 == 0) )); then 
		echo "FizzBuzz"
	elif (( "$count" % 3 == 0 )); then
		echo "Fizz"
	elif (( "$count" % 5 == 0 )); then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count++))
done 
