#!/usr/bin/env bash
# This script prints bad luck on the 4th iteration, good luck on the 8th and Best school for all the others

count=1

while ((count <= 10)) 
do
	if ((count == 4)); then
		echo "bad luck"
	elif ((count == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
