#!/usr/bin/env bash
# This script prints bad luck on the 4th iteration, good luck on the 8th an>

count=1

while ((count <= 20))
do
	case $count in 
		4)
			printf "4\nbad luck from China\n"
			;;

		9)
			printf "9\nbad luck from Japan\n"
			;;

		17)
			printf "17\nbad luck from Italy\n"
			;;

		*)
			echo "$count"
			;;
	esac
	((count++))
done
