#!/usr/bin/env bash
#This script displays hours from 0 to 12 and minutes from 1 to 59
hour=0


while ((hour <= 12))
do
	echo "Hour: $hour"
	minnute=1
	while ((minute <= 59))
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
